### ISSUE TITLE
Unexpected AssertionError on introspecting GraphQL

### ISSUE THREAD

**Issue by playpauseandstop** [vmagamedov/hiku#25]
After upgrading to `Hiku==0.4.0rc6` got unexpected `AssertionError` on introspecting GraphQL via _GraphiQL App_,

```
Traceback (most recent call last):
  File "/app/api/graph/utils.py", line 80, in process_query_graph
    result = await engine.execute(graph, query, context)
  File "/usr/local/lib/python3.6/dist-packages/hiku/executors/asyncio.py", line 23, in process
    queue.progress(done)
  File "/usr/local/lib/python3.6/dist-packages/hiku/executors/queue.py", line 38, in progress
    callback()
  File "/usr/local/lib/python3.6/dist-packages/hiku/engine.py", line 260, in <lambda>
    _result_proc())
  File "/usr/local/lib/python3.6/dist-packages/hiku/engine.py", line 72, in store_fields
    query_result = list(query_result)
  File "/usr/local/lib/python3.6/dist-packages/hiku/introspection/graphql.py", line 203, in input_value_info
    default = print_ast(ast_from_value(option.default))
  File "/usr/local/lib/python3.6/dist-packages/graphql/utils/ast_from_value.py", line 49, in ast_from_value
    assert isinstance(value, dict)
AssertionError
```

Introspection query pasted below

<details>

```
  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
```

</details>

----

High level graph instantiated as,

```py
HIGH_LEVEL_GRAPH = apply(Graph([
    ...
]), [AsyncGraphQLIntrospection()])
```

Please let me know if you need more details from my side to reproduce the error.

**Comment by vmagamedov** [comment]
This error is inside of graphql-core library and it is indicating that Option's default value has invalid type. Unfortunately, this is all I can say by looking at this traceback. In order to find out which Option causes such errors, try to debug two last lines from your traceback.

Additional information: https://facebook.github.io/graphql/#sec-The-__InputValue-Type

> defaultValue may return a String encoding (using the GraphQL language) of the default value used by this input value in the condition a value is not provided at runtime. If this input value has no default value, returns null.

In the previous versions of Hiku, default values was encoded simply by using `str()`, that's why this error was hidden.

**Comment by playpauseandstop** [comment]
Issue caused by next option,

```py
    Option('ids', Sequence[String], default=()),
```

Fixed with,

```py
    Option('ids', Optional[Sequence[String]], default=None),
```
Going forward it would be nice to see meaningful error on which option is wrong one instead of empty `AssertionError`.

Behind that closing that as `wontfix`
